services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:c11ca42-tensorrt
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: "128mb"
    runtime: nvidia
    environment:
      - YOLO_MODELS=yolov7x-640
      - USE_FP16=false
    ports:
      - "8554:8554"
      - "8555:8555"
      - "8555:8555/udp"
      - "5000:5000"
    volumes:
      - ./config.yml:/config/config.yml
      - ./coco-labels-91.txt:/config/coco-labels-91.txt
      - ./Clips:/media/frigate/clips
      - ./Recordings:/media/frigate/recordings
      - ./Snapshots:/media/frigate/snapshots
